# Generated by Django 5.0.6 on 2024-05-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerodisponible',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
