# Generated by Django 5.0.6 on 2024-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0003_persona_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerodisponible',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
